#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# launch picom
picom -b &

# set monitor layout
xrandr --output DP1 --auto --output HDMI1 --auto --above DP1 &

# set wallpaper
feh --bg-scale --no-fehbg ~/.config/wallpaper.jpg &

# launch polybar
$HOME/.config/polybar/launch.sh

bspc monitor HDMI1 -d 4 5 6
bspc monitor DP1 -d 1 2 3

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
